"use client";
import {useState} from "react";
export default function Page(){
 const[plz,setPlz]=useState(""),[garages,setGarages]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function search(e){e?.preventDefault();if(!plz.trim())return;setLoading(true);setError("");try{const r=await fetch("/api/oficinas?plz="+encodeURIComponent(plz.trim()));const d=await r.json();if(!r.ok)throw Error(d.error||"Busca indisponível");setGarages(d.garages||[]);if(!(d.garages||[]).length)setError("Nenhuma oficina cadastrada nessa área. Tente um CEP próximo.");setTimeout(()=>document.getElementById("garageResults")?.scrollIntoView({behavior:"smooth"}),50)}catch(x){setError(x.message)}finally{setLoading(false)}}
 return <main className="shopDirectory whiteDirectory"><header className="directoryTop"><a className="brand brandLink" href="/">TOTAL <b>CARS</b><span>.CH</span></a><nav><a href="/pneus">Pneus & rodas</a><a href="/pecas">Peças</a><a href="/">Início</a></nav></header>
 <section className="shopHero whiteHero"><p className="eyebrow">TOTAL CARS · OFICINAS</p><h1>Encontre oficinas perto de você</h1><p>Digite um CEP/PLZ suíço. A busca procura oficinas e serviços automotivos em até aproximadamente 15 km.</p><form className="plzFinder" onSubmit={search}><label>SEU CEP / PLZ</label><input value={plz} onChange={e=>setPlz(e.target.value)} inputMode="numeric" placeholder="Ex.: 9464"/><button disabled={loading}>{loading?"PROCURANDO…":"ENCONTRAR OFICINAS →"}</button></form>{error&&<p className="directoryError">{error}</p>}</section>
 <section id="garageResults" className="garageGrid centeredDirectory">{garages.map(g=><article className="garageCard" key={g.id}><div className="garagePreview">🔧</div><div><small>{g.distance!=null?g.distance.toFixed(1)+" KM":"OFICINA"}</small><h2>{g.name}</h2><p>{g.address||"Endereço disponível no mapa"}</p><div className="contactLinks">{g.phone&&<a href={"tel:"+g.phone}>☎ TELEFONE</a>}{g.email&&<a href={"mailto:"+g.email}>✉ E-MAIL</a>}{g.website&&<a href={g.website} target="_blank" rel="noreferrer">SITE ↗</a>}{g.lat&&g.lon&&<a href={"https://www.google.com/maps/search/?api=1&query="+g.lat+","+g.lon} target="_blank" rel="noreferrer">MAPA ↗</a>}</div></div></article>)}</section>
 </main>
}