"use client";
import {useState} from "react";
const garages=[
{name:"Garage Fuchs GmbH",plz:"9470",city:"Buchs SG",address:"Churerstrasse 84, 9470 Buchs SG",phone:"+41 81 756 46 36",email:"info@fuchs-garage.ch",site:"https://www.fuchs-garage.ch/"},
{name:"Seegarage Buchs GmbH",plz:"9470",city:"Buchs SG",address:"Moosweg 11, 9470 Buchs SG",phone:"+41 81 740 07 07",email:"info@seegarage-buchs.ch",site:"https://www.seegarage-buchs.ch/"},
{name:"Garage J. Müntener AG",plz:"9470",city:"Buchs SG",address:"Mühleäulistrasse 16, 9470 Buchs SG",phone:"",email:"",site:"https://dealer.suzuki.ch/garage-muentener-buchs/de/"},
{name:"Garage Duss",plz:"9470",city:"Buchs SG",address:"Haldengasse 34, 9470 Buchs SG",phone:"+41 81 756 15 73",email:"duss@dusshistoric.ch",site:"https://www.dusshistoric.ch/"},
{name:"Auto Linher Sennwald",plz:"9466",city:"Sennwald",address:"Simon-Frick-Strasse 18, 9466 Sennwald",phone:"+41 81 533 59 10",email:"verkauf@motolinher.ch",site:"https://www.motolinher.ch/werkstatt/"}
];
export default function Page(){const[q,setQ]=useState("");const norm=q.trim().toLowerCase();const shown=norm?garages.filter(g=>(g.plz+" "+g.city+" "+g.name+" "+g.address).toLowerCase().includes(norm)):garages;return <main className="shopDirectory"><header className="directoryTop"><a className="brand brandLink" href="/">TOTAL <b>CARS</b><span>.CH</span></a><nav><a href="/pecas">Peças</a><a href="/pneus">Pneus & rodas</a><a href="/revista">Revista</a></nav></header><section className="shopHero"><p className="eyebrow">TOTAL CARS LOCAL</p><h1>Oficinas perto de você</h1><p>Digite seu CEP/PLZ ou cidade. Exemplo: 9464 Rüthi, 9466 Sennwald ou 9470 Buchs.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite CEP/PLZ, cidade ou oficina…"/></section><section className="garageGrid">{shown.map(g=><article className="garageCard" key={g.name}><a href={g.site} target="_blank" rel="noreferrer" className="garagePreview"><img src={"https://www.google.com/s2/favicons?domain="+new URL(g.site).hostname+"&sz=128"} alt=""/></a><div><small>{g.plz} · {g.city}</small><h2>{g.name}</h2><p>{g.address}</p><div className="contactLinks">{g.phone&&<a href={"tel:"+g.phone.replace(/\s/g,"")}>☎ {g.phone}</a>}{g.email&&<a href={"mailto:"+g.email}>✉ {g.email}</a>}<a href={"https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(g.address)} target="_blank" rel="noreferrer">⌖ MAPA</a><a href={g.site} target="_blank" rel="noreferrer">SITE →</a></div></div></article>)}</section></main>}