"use client";
import {useEffect,useState} from "react";
const welcome={role:"ai",text:"Olá! Sou o Total Cars AI. Informe o carro e descreva o problema. Vou acompanhar o contexto da conversa e investigar com você por etapas."};
export default function Diagnostico(){
 const [input,setInput]=useState(""); const [msgs,setMsgs]=useState([welcome]); const [loading,setLoading]=useState(false); const [err,setErr]=useState("");
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("tc_diag")||"null");if(x?.length)setMsgs(x)}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("tc_diag",JSON.stringify(msgs))}catch{}},[msgs]);
 async function send(){const q=input.trim();if(!q||loading)return;const user={role:"user",text:q};const next=[...msgs,user];setMsgs(next);setInput("");setLoading(true);setErr("");
 try{const r=await fetch("/api/diagnostico",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next})});const d=await r.json();if(!r.ok)throw new Error(d?.error||"Falha na IA");setMsgs(m=>[...m,{role:"ai",text:d.text}])}
 catch(e){setErr(e.message||"Erro");setMsgs(m=>[...m,{role:"ai",text:"Não consegui responder agora. "+(e.message||"Tente novamente.")}])}finally{setLoading(false)}}
 function reset(){if(!confirm("Excluir toda a conversa antiga?"))return;localStorage.removeItem("tc_diag");setMsgs([welcome]);setInput("");setErr("")}
 return <main className="chatPage"><header className="chatTop"><a href="/" className="premiumLogo"><span>TOTAL</span> CARS<em>.CH</em></a><div><button className="deleteChat" onClick={reset}>🗑 EXCLUIR CONVERSA</button><button onClick={reset}>+ NOVA CONVERSA</button></div></header><div className="chatShell"><aside><b>DIAGNÓSTICO GPT</b><p>Conversa atual</p><small>O histórico fica salvo neste navegador.</small><button className="deleteChat sideDelete" onClick={reset}>🗑 Excluir conversa antiga</button></aside><section className="chatMain"><div className="chatTitle"><span>TC</span><div><b>Total Cars AI</b><small>Diagnóstico automotivo com GPT</small></div></div>{err&&<div className="chatError">⚠ {err}</div>}<div className="messages">{msgs.map((m,i)=><div className={"message "+m.role} key={i}><b>{m.role==="ai"?"TOTAL CARS AI":"VOCÊ"}</b><p>{m.text}</p></div>)}{loading&&<div className="message ai"><b>TOTAL CARS AI</b><p>Analisando...</p></div>}</div><div className="chatInput"><textarea value={input} disabled={loading} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ex.: Audi A6 3.0 TDI faz clec-clec na partida..."/><button disabled={loading} onClick={send}>{loading?"AGUARDE...":"ENVIAR ↑"}</button></div><small className="chatDisclaimer">Triagem informativa. Problemas de segurança exigem inspeção profissional.</small></section></div></main>
}