"use client";
import {useEffect,useRef,useState} from "react";

const cars={
"Audi":{models:["A6 / S6 / RS6","A4 / S4 / RS4","A3 / S3","Q5","Q7"],versions:["A6 C7 (2011–2018)","A6 C6 (2004–2011)","A6 C8 (2018–2024)","A4 B9 (2015–2024)","A4 B8 (2008–2015)"],motors:["3.0 TDI V6 Quattro","2.0 TDI (150/190 CV)","2.0 TFSI Turbo","3.0 TFSI Supercharged"]},
"Volkswagen":{models:["Golf VII / VIII","Passat Variant","Tiguan","Touareg"],versions:["Golf VII (2012–2020)","Passat B8 (2014–2023)","Tiguan II (2016–2024)"],motors:["2.0 TDI (150/190 CV)","2.0 TSI GTI/R","1.4 / 1.5 TSI"]},
"BMW":{models:["Série 3 (320d/330d)","Série 5 Touring","X3 xDrive","X5 xDrive"],versions:["G20 / G21 Touring (2019–2024)","F30 / F31 Touring (2011–2019)"],motors:["2.0d B47 (320d)","3.0d 6 Cilindros (330d/530d)","2.0 Turbo Gasolina"]},
"Mercedes-Benz":{models:["Classe C (C220d)","Classe E Station","GLC 4MATIC"],versions:["W205 / S205 (2014–2021)","S213 (2016–2023)"],motors:["2.2 / 2.0 CDI Diesel","3.0 V6 Diesel","2.0 Turbo Gasolina"]},
"Porsche":{models:["Macan","Cayenne","911 Carrera"],versions:["Macan II (2018–2024)","Cayenne E3 (2017–2024)"],motors:["3.0 V6 Turbo","2.9 V6 BiTurbo","E-Hybrid"]},
"Skoda":{models:["Octavia Combi","Superb Combi 4x4","Kodiaq"],versions:["Octavia IV (2020–2024)","Octavia III (2012–2020)"],motors:["2.0 TDI (150/200 CV 4x4)","1.5 TSI"]},
"Seat / Cupra":{models:["Cupra Formentor","Leon Sportstourer"],versions:["Formentor VZ 310 CV","Leon KL (2020–2024)"],motors:["2.0 TSI (310 CV)","1.5 eTSI"]},
"Toyota":{models:["RAV4 Hybrid","Corolla Touring Sports"],versions:["RAV4 XA50 (2018–2024)","Corolla E210"],motors:["2.5 Hybrid e-CVT (AWD-i)","2.0 Hybrid"]},
"Tesla":{models:["Model 3","Model Y"],versions:["Long Range Dual Motor","Performance AWD"],motors:["Dual Motor Elétrico"]},
"Ford":{models:["Focus Turnier","Kuga PHEV"],versions:["Focus Mk4 (2018–2024)","Kuga Mk3"],motors:["2.0 EcoBlue Diesel","2.5 Duratec PHEV"]},
"Volvo":{models:["XC60 Recharge","V60 Cross Country"],versions:["XC60 II (2017–2024)","V60 II"],motors:["T8 Plug-in Hybrid (455 CV)","B5 AWD"]}
};
const audi={brand:"Audi",model:"A6 / S6 / RS6",version:"A6 C7 (2011–2018)",year:"2015",motor:"3.0 TDI V6 Quattro"};
const initial=[
{role:"user",text:"meu audi quebrou a mola traseira"},
{role:"ai",text:"Entendi — no seu Audi A6 3.0 TDI, então aquele problema que você comentou na traseira era a mola traseira quebrada, não bolsa pneumática.\n\nEvite rodar assim, principalmente se a mola saiu da posição ou existe uma ponta quebrada encostando perto do pneu. Ela pode danificar o pneu, amortecedor ou outros componentes. O ideal é trocar a mola e verificar também prato/borracha de apoio e amortecedor."},
{role:"user",text:"sim saiu do suporte"},
{role:"ai",alert:"Aí muda bastante: se a mola traseira saiu do suporte/prato, eu não recomendo continuar rodando com o Audi até verificar. A ponta solta de aço pode furar a lateral do pneu ou danificar a tubulação de freio.",video:true}
];
export default function Diagnostico(){
 const [car,setCar]=useState(audi),[msgs,setMsgs]=useState(initial),[input,setInput]=useState(""),[loading,setLoading]=useState(false),[side,setSide]=useState(false); const end=useRef(null);
 useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[msgs,loading]);
 const summary=`${car.brand} ${car.model} (${car.year}) ${car.motor}`;
 function brand(v){const d=cars[v];setCar({brand:v,model:d.models[0],version:d.versions[0],year:car.year,motor:d.motors[0]})}
 async function send(q=input){q=q.trim();if(!q||loading)return;setMsgs(m=>[...m,{role:"user",text:q}]);setInput("");setLoading(true);
 try{const history=[...msgs,{role:"user",text:`Veículo selecionado: ${summary}; geração/versão: ${car.version}. Pergunta do usuário: ${q}`}];const r=await fetch("/api/diagnostico",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:history})});const d=await r.json();if(!r.ok)throw Error(d.error||"Falha na IA");setMsgs(m=>[...m,{role:"ai",text:d.text}])}catch(e){setMsgs(m=>[...m,{role:"ai",alert:e.message||"Erro no diagnóstico."}])}finally{setLoading(false)}}
 function example(){setCar(audi);setMsgs(initial);setSide(false)}
 function apply(){send(`Selecionei o meu carro: ${summary}, versão ${car.version}. Como você pode me ajudar?`);setSide(false)}
 function mic(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert("Use Chrome ou Edge para reconhecimento de voz.");const r=new SR();r.lang="pt-BR";r.onresult=e=>{const t=e.results[0][0].transcript;setInput(t);send(t)};r.start()}
 return <main className="cleanDiag">
 <header className="cleanHead"><div className="cleanBrand"><button className="mobileMenu" onClick={()=>setSide(!side)}>☰</button><a href="/"><span className="carIcon">🚗</span><div><b>TOTAL<span>CARS</span>.CH</b><small>Oficina Mecânica & Diagnóstico com Vídeo no Chat</small></div><em>🇨🇭 SUÍÇA</em></a></div><div className="headActions"><button onClick={example}>↻ <span>Caso Audi A6</span></button><a href="https://wa.me/41790000000" target="_blank">● Agendar Oficina</a></div></header>
 <div className="cleanWork">{side&&<div className="sideBackdrop" onClick={()=>setSide(false)}/>}<aside className={side?"cleanSide open":"cleanSide"}><div className="sideTitle">🎚️ <b>Escolha o seu Carro</b><button onClick={()=>setSide(false)}>×</button></div><div className="audiPreset" onClick={example}><strong>⚡ CASO DA FOTO (1 TOQUE) <i>→</i></strong><b>Audi A6 3.0 TDI Quattro</b><small>Mola traseira quebrada fora do prato</small></div><div className="carForm">
 {["Marca","Modelo","Geração / Versão","Ano","Motor / Tração"].map((lab,i)=><label key={lab}>{lab}: {i===0?<select value={car.brand} onChange={e=>brand(e.target.value)}>{Object.keys(cars).map(x=><option key={x}>{x}</option>)}</select>:i===1?<select value={car.model} onChange={e=>setCar({...car,model:e.target.value})}>{cars[car.brand].models.map(x=><option key={x}>{x}</option>)}</select>:i===2?<select value={car.version} onChange={e=>setCar({...car,version:e.target.value})}>{cars[car.brand].versions.map(x=><option key={x}>{x}</option>)}</select>:i===3?<select value={car.year} onChange={e=>setCar({...car,year:e.target.value})}>{["2022","2020","2018","2016","2015","2014","2013","2012","2010","2008"].map(x=><option key={x}>{x}</option>)}</select>:<select value={car.motor} onChange={e=>setCar({...car,motor:e.target.value})}>{cars[car.brand].motors.map(x=><option key={x}>{x}</option>)}</select>}</label>)}
 <div className="selectedCard"><small>CARRO SELECIONADO:</small><b>{summary}</b><span>● Pronto para o diagnóstico</span></div><button className="applyCar" onClick={apply}>✓ Consultar Este Carro no Chat</button></div><footer>TotalCars • Suíça <b>CHF</b></footer></aside>
 <section className="cleanChat"><div className="chatSub"><span>●</span><b>{summary}</b><em>• Suspensão & Diagnóstico</em><button onClick={example}>↻ Reiniciar</button></div><div className="cleanMessages">{msgs.map((m,i)=><div className={"cleanMsg "+m.role} key={i}>{m.role==="ai"&&<span className="wrench">🔧</span>}<div>{m.alert&&<p className="danger">{m.alert}</p>}{m.text&&<p>{m.text}</p>}{m.video&&<><b className="videoTitle">Audi A6 Quattro 2012–2018 — troca da mola traseira quebrada ↗</b><div className="cleanVideo"><iframe src="https://www.youtube-nocookie.com/embed/R9K2m1iO5cI?rel=0&modestbranding=1" title="Audi A6 rear springs" allowFullScreen/></div><div className="estimate"><span>Par de Molas Novas:<b>CHF 140.– a 195.–</b></span><span>Mão de obra oficina:<b>CHF 180.– a 240.–</b></span><span>Teste MFK Suíça:<b>Reprovação grave</b></span></div></>}</div></div>)}{loading&&<div className="cleanMsg ai"><span className="wrench">⚙️</span><div className="typing">Consultando mecânica... <i>● ● ●</i></div></div>}<div ref={end}/></div>
 <div className="cleanChips"><b>SUGESTÕES:</b>{["🔩 Quebrou a mola traseira","⚠️ Sim, saiu do suporte","🛑 Posso rodar assim?","💰 Preço em CHF"].map((x,i)=><button key={x} onClick={()=>send(["meu audi quebrou a mola traseira","sim saiu do suporte","posso rodar até a oficina com ela quebrada?","quanto custa a troca da mola na Suíça em CHF?"][i])}>{x}</button>)}</div>
 <div className="cleanInput"><form onSubmit={e=>{e.preventDefault();send()}}><button type="button" className="mic" onClick={mic}>🎙</button><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Digite o defeito, sintoma ou código (ex: mola traseira quebrada, barulho, P0299)..."/><button className="send">↑</button></form><small>TotalCars.ch • Diagnóstico automotivo com vídeo de reparo e orçamento em francos suíços (CHF).</small></div></section></div></main>
}