const hero="https://uploads.audi.com/system/production/media/117722/images/44c10cf1e8e8d9c830feaff0a7ea977994572844/A232980_web_2880.jpg?1698535865=";
const categories=[["Comprar carros","Novos, usados e oportunidades","/marketplace"],["Trocar veículo","Anúncios que aceitam troca","/marketplace"],["Diagnóstico IA","Converse sobre falhas e sintomas","/diagnostico"],["Peças","Novas, usadas e fornecedores","/pecas"],["Pneus & rodas","Lojas, ofertas e serviços","/pneus"],["Oficinas","Mecânicas e especialistas","/oficinas"],["Desmanches","Auto-recycling e peças usadas","/desmanches"],["Eventos","Encontros automotivos","/eventos"]];
export default function Home(){return <main className="tc">
<header className="premiumTop"><a className="premiumLogo" href="/"><span>TOTAL</span> CARS<em>.CH</em></a><nav><a href="/marketplace">CARROS</a><a href="/pecas">PEÇAS</a><a href="/oficinas">OFICINAS</a><a href="/revista">REVISTA</a><a href="/fichas">FICHAS</a><a href="/eventos">EVENTOS</a></nav><div className="topActions"><a className="langPill" href="#">PT · DE</a><a href="/garagem">♡ GARAGEM</a><a className="sellBtn" href="/anunciar">+ ANUNCIAR</a></div></header>
<section className="photoHero" style={{backgroundImage:`linear-gradient(90deg,rgba(5,7,10,.96) 0%,rgba(5,7,10,.78) 38%,rgba(5,7,10,.08) 75%),url("${hero}")`}}><div className="premiumHeroContent"><span className="heroKicker">TOTAL CARS · SWITZERLAND</span><h1>PAIXÃO POR<br/><i>CARROS.</i><br/>SEM LIMITES.</h1><p>Marketplace, diagnóstico inteligente, peças, oficinas e a nova revista automotiva global.</p><div className="premiumSearch"><select defaultValue=""><option value="" disabled>Marca</option><option>Audi</option><option>BMW</option><option>Mercedes-Benz</option><option>Porsche</option><option>Volkswagen</option></select><input placeholder="Modelo ou palavra-chave"/><select defaultValue=""><option value="" disabled>Preço até</option><option>CHF 5'000</option><option>CHF 10'000</option><option>CHF 25'000</option><option>CHF 50'000+</option></select><a href="/marketplace">BUSCAR</a></div><div className="heroLinks"><a href="/marketplace">🔥 OFERTAS</a><a href="/marketplace">✓ COM MFK</a><a href="/marketplace">↔ ACEITA TROCA</a></div></div><a className="aiFloat" href="/diagnostico"><span>AI</span><div><b>DIAGNÓSTICO TOTAL CARS</b><small>Converse sobre o problema do seu carro →</small></div></a><small className="photoCredit">Imagem editorial: AUDI AG</small></section>
<section className="headlineBar"><b>AGORA NO TOTAL CARS</b><span>CARROS</span><span>LANÇAMENTOS</span><span>SUÍÇA</span><span>CHINA</span><span>ELÉTRICOS</span><span>SUPERCARROS</span></section>
<section className="premiumSection"><div className="sectionHead"><div><span>EXPLORE</span><h2>Seu universo automotivo.</h2></div><a href="/marketplace">VER TODOS →</a></div><div className="premiumGrid">{categories.map(([t,d,h],n)=><a href={h} className="premiumTile" key={t}><span className="tileNo">0{n+1}</span><h3>{t}</h3><p>{d}</p><b>EXPLORAR →</b></a>)}</div></section>
<section className="magTeaser" style={{backgroundImage:`linear-gradient(90deg,#07090ce8,#07090c66),url("${hero}")`}}><div><span className="heroKicker">TOTAL CARS MAGAZINE</span><h2>Uma revista para<br/>realmente folhear.</h2><p>Notícias, lançamentos, testes, mercado suíço e o melhor do mundo automotivo em uma experiência editorial.</p><a href="/revista">ABRIR A REVISTA →</a></div></section>
<section className="aiBand"><div><span className="heroKicker">TOTAL CARS INTELLIGENCE</span><h2>Diagnóstico em forma de conversa.</h2><p>Escreva o problema, continue perguntando e mantenha o histórico. Vídeos relacionados aparecem dentro da própria conversa.</p><a href="/diagnostico">CONVERSAR AGORA →</a></div><div className="aiOrb"><span>TC</span><b>AI</b></div></section>
<section className="sellBand"><div><small>VENDA SEU CARRO</small><h2>Seu próximo negócio começa aqui.</h2><p>Anuncie para compradores em toda a Suíça.</p></div><a href="/anunciar">ANUNCIAR GRÁTIS →</a></section>
<footer className="premiumFooter"><div className="premiumLogo"><span>TOTAL</span> CARS<em>.CH</em></div><div>Carros · Peças · Oficinas · Revista · Fichas · Eventos</div><small>© 2026 Total Cars Switzerland</small></footer></main>}