"use client";
import {useEffect,useState} from "react";

const hero="https://uploads.audi.com/system/production/media/117722/images/44c10cf1e8e8d9c830feaff0a7ea977994572844/A232980_web_2880.jpg?1698535865=";
const copy={
pt:{nav:["CARROS","PEÇAS","OFICINAS","REVISTA","FICHAS","EVENTOS"],garage:"♡ GARAGEM",sell:"+ ANUNCIAR",kicker:"TOTAL CARS · SUÍÇA",title:["PAIXÃO POR","CARROS.","SEM LIMITES."],intro:"Marketplace, diagnóstico inteligente, peças, oficinas e a nova revista automotiva global.",brand:"Marca",model:"Modelo ou palavra-chave",price:"Preço até",search:"BUSCAR",offers:["🔥 OFERTAS","✓ COM MFK","↔ ACEITA TROCA"],diag:"DIAGNÓSTICO TOTAL CARS",diagSub:"Converse sobre o problema do seu carro →",now:"AGORA NO TOTAL CARS",head:["CARROS","LANÇAMENTOS","SUÍÇA","CHINA","ELÉTRICOS","SUPERCARROS"],explore:"EXPLORE",universe:"Seu universo automotivo.",all:"VER TODOS →",cats:[["Comprar carros","Novos, usados e oportunidades"],["Trocar veículo","Anúncios que aceitam troca"],["Diagnóstico IA","Converse sobre falhas e sintomas"],["Peças","Novas, usadas e fornecedores"],["Pneus & rodas","Lojas, ofertas e serviços"],["Oficinas","Mecânicas e especialistas"],["Desmanches","Auto-recycling e peças usadas"],["Eventos","Encontros automotivos"]],go:"EXPLORAR →",mag:"Uma revista para realmente folhear.",magp:"Notícias, lançamentos, testes, mercado suíço e o melhor do mundo automotivo em uma experiência editorial.",open:"ABRIR A REVISTA →",ait:"Diagnóstico em forma de conversa.",aip:"Escreva o problema e continue perguntando. O GPT mantém o contexto da conversa.",talk:"CONVERSAR AGORA →",sellk:"VENDA SEU CARRO",sellt:"Seu próximo negócio começa aqui.",sellp:"Anuncie para compradores em toda a Suíça.",sellb:"ANUNCIAR GRÁTIS →"},
de:{nav:["AUTOS","TEILE","WERKSTÄTTEN","MAGAZIN","DATEN","EVENTS"],garage:"♡ GARAGE",sell:"+ INSERIEREN",kicker:"TOTAL CARS · SCHWEIZ",title:["LEIDENSCHAFT FÜR","AUTOS.","OHNE GRENZEN."],intro:"Marktplatz, intelligente Diagnose, Teile, Werkstätten und das neue globale Automagazin.",brand:"Marke",model:"Modell oder Suchbegriff",price:"Preis bis",search:"SUCHEN",offers:["🔥 ANGEBOTE","✓ MIT MFK","↔ TAUSCH MÖGLICH"],diag:"TOTAL CARS DIAGNOSE",diagSub:"Sprechen Sie über das Problem Ihres Autos →",now:"JETZT BEI TOTAL CARS",head:["AUTOS","NEUHEITEN","SCHWEIZ","CHINA","ELEKTRO","SUPERCARS"],explore:"ENTDECKEN",universe:"Ihre automobile Welt.",all:"ALLE ANSEHEN →",cats:[["Autos kaufen","Neu, gebraucht und Angebote"],["Fahrzeug tauschen","Inserate mit Tauschmöglichkeit"],["KI-Diagnose","Über Fehler und Symptome sprechen"],["Teile","Neu, gebraucht und Anbieter"],["Reifen & Felgen","Shops, Angebote und Service"],["Werkstätten","Garagen und Spezialisten"],["Autoverwertung","Recycling und Gebrauchtteile"],["Events","Automobiltreffen"]],go:"ENTDECKEN →",mag:"Ein Magazin zum echten Durchblättern.",magp:"News, Neuheiten, Tests, Schweizer Markt und die automobile Welt als redaktionelles Erlebnis.",open:"MAGAZIN ÖFFNEN →",ait:"Diagnose als Gespräch.",aip:"Beschreiben Sie das Problem und fragen Sie weiter. GPT behält den Gesprächskontext.",talk:"JETZT SPRECHEN →",sellk:"AUTO VERKAUFEN",sellt:"Ihr nächstes Geschäft beginnt hier.",sellp:"Inserieren Sie für Käufer in der ganzen Schweiz.",sellb:"KOSTENLOS INSERIEREN →"}
};
const hrefs=["/marketplace","/marketplace","/diagnostico","/pecas","/pneus","/oficinas","/desmanches","/eventos"];
const navhrefs=["/marketplace","/pecas","/oficinas","/revista","/fichas","/eventos"];
export default function Home(){
const [lang,setLang]=useState("pt");
useEffect(()=>{const l=localStorage.getItem("tc_lang");if(copy[l])setLang(l)},[]);
const setLanguage=l=>{setLang(l);localStorage.setItem("tc_lang",l)};
const extra={fr:{...copy.pt,nav:["VOITURES","PIÈCES","GARAGES","MAGAZINE","FICHES","ÉVÉNEMENTS"],garage:"♡ GARAGE",sell:"+ PUBLIER",kicker:"TOTAL CARS · SUISSE",title:["PASSION POUR","LES VOITURES.","SANS LIMITES."],intro:"Marketplace, diagnostic intelligent, pièces, garages et magazine automobile mondial.",brand:"Marque",model:"Modèle ou mot-clé",price:"Prix jusqu’à",search:"RECHERCHER",diag:"DIAGNOSTIC TOTAL CARS",diagSub:"Parlez du problème de votre voiture →"},it:{...copy.pt,nav:["AUTO","RICAMBI","OFFICINE","RIVISTA","SCHEDE","EVENTI"],garage:"♡ GARAGE",sell:"+ PUBBLICA",kicker:"TOTAL CARS · SVIZZERA",title:["PASSIONE PER","LE AUTO.","SENZA LIMITI."],intro:"Marketplace, diagnosi intelligente, ricambi, officine e rivista automobilistica globale.",brand:"Marca",model:"Modello o parola chiave",price:"Prezzo fino a",search:"CERCA",diag:"DIAGNOSI TOTAL CARS",diagSub:"Parla del problema della tua auto →"},en:{...copy.pt,nav:["CARS","PARTS","GARAGES","MAGAZINE","SPECS","EVENTS"],garage:"♡ GARAGE",sell:"+ LIST CAR",kicker:"TOTAL CARS · SWITZERLAND",title:["PASSION FOR","CARS.","WITHOUT LIMITS."],intro:"Marketplace, intelligent diagnostics, parts, garages and a global automotive magazine.",brand:"Make",model:"Model or keyword",price:"Price up to",search:"SEARCH",diag:"TOTAL CARS DIAGNOSTICS",diagSub:"Talk about your car problem →"},es:{...copy.pt,nav:["COCHES","PIEZAS","TALLERES","REVISTA","FICHAS","EVENTOS"],garage:"♡ GARAJE",sell:"+ PUBLICAR",kicker:"TOTAL CARS · SUIZA",title:["PASIÓN POR","LOS COCHES.","SIN LÍMITES."],intro:"Marketplace, diagnóstico inteligente, piezas, talleres y revista mundial del automóvil.",brand:"Marca",model:"Modelo o palabra clave",price:"Precio hasta",search:"BUSCAR",diag:"DIAGNÓSTICO TOTAL CARS",diagSub:"Habla sobre el problema de tu coche →"}}; const allCopy={...copy,...extra}; const t=allCopy[lang]||copy.pt;
return <main className="tc">
<header className="premiumTop"><a className="premiumLogo refLogo" href="/"><span className="gauge">◒</span><span className="logoWords"><b>TOTAL <i>CARS</i><em>.CH</em></b><small>SWITZERLAND 🇨🇭</small></span></a><nav>{t.nav.map((x,i)=><a key={x} href={navhrefs[i]}><span className="navIcon">{["▣","⚙","⌁","▤","▧","▦"][i]}</span>{x}</a>)}<a href="/"><span className="navIcon">•••</span>MAIS</a></nav><div className="topActions"><label className="languageMenu"><span>🌐</span><select value={lang} onChange={e=>setLanguage(e.target.value)}><option value="pt">🇧🇷 Português</option><option value="de">🇩🇪 Deutsch</option><option value="fr">🇫🇷 Français</option><option value="it">🇮🇹 Italiano</option><option value="en">🇬🇧 English</option><option value="es">🇪🇸 Español</option></select></label><a href="/garagem">{t.garage}</a><a className="sellBtn" href="/anunciar">{t.sell}</a></div></header>
<section className="photoHero referenceHero" style={{backgroundImage:`url("${hero}")`}}><div className="premiumHeroContent"><span className="heroKicker">← &nbsp; {t.kicker} 🇨🇭</span><h1>{t.title[0]}<br/><i>{t.title[1]}</i><br/>{t.title[2]}</h1><p>{t.intro}</p><div className="heroSearchWrap"><div className="premiumSearch"><select defaultValue=""><option value="" disabled>{t.brand}</option><option>Audi</option><option>BMW</option><option>Mercedes-Benz</option><option>Porsche</option><option>Volkswagen</option></select><input placeholder={t.model}/><select defaultValue=""><option value="" disabled>{t.price}</option><option>CHF 5'000</option><option>CHF 10'000</option><option>CHF 25'000</option><option>CHF 50'000+</option></select><a href="/marketplace">⌕ &nbsp; {t.search}</a></div><div className="heroLinks">{t.offers.map(x=><a href="/marketplace" key={x}>{x}</a>)}</div></div><a className="aiFloat" href="/diagnostico"><span>AI</span><div><b>{t.diag}</b><small>{t.diagSub}</small></div></a><div className="heroDock"><a href="/diagnostico"><b className="thumb carThumb">🚘</b><span><strong>DIAGNÓSTICO GPT</strong><small>Descubra o problema do seu carro com IA</small></span><i>›</i></a><a href="/pecas"><b className="thumb tireThumb">◉</b><span><strong>PEÇAS E PNEUS</strong><small>Novos e usados, as melhores ofertas</small></span><i>›</i></a><a href="/oficinas"><b className="thumb garageThumb">🔧</b><span><strong>OFICINAS</strong><small>Encontre oficinas perto de você</small></span><i>›</i></a><a href="/revista"><b className="thumb magazineThumb">🏎️</b><span><strong>REVISTA</strong><small>Notícias, lançamentos e testes</small></span><i>›</i></a><a href="/eventos"><b className="thumb eventThumb">🗓️</b><span><strong>EVENTOS</strong><small>Encontros, feiras e eventos automotivos</small></span><i>›</i></a></div><small className="photoCredit">Imagem editorial: AUDI AG</small></section>
<section className="headlineBar"><b>{t.now}</b>{t.head.map(x=><span key={x}>{x}</span>)}</section>
<section className="premiumSection"><div className="sectionHead"><div><span>{t.explore}</span><h2>{t.universe}</h2></div><a href="/marketplace">{t.all}</a></div><div className="premiumGrid">{t.cats.map(([a,b],i)=><a href={hrefs[i]} className="premiumTile" key={a}><span className="tileNo">0{i+1}</span><h3>{a}</h3><p>{b}</p><b>{t.go}</b></a>)}</div></section>
<section className="magTeaser" style={{backgroundImage:`linear-gradient(90deg,#07090ce8,#07090c66),url("${hero}")`}}><div><span className="heroKicker">TOTAL CARS MAGAZINE</span><h2>{t.mag}</h2><p>{t.magp}</p><a href="/revista">{t.open}</a></div></section>
<section className="aiBand"><div><span className="heroKicker">TOTAL CARS INTELLIGENCE</span><h2>{t.ait}</h2><p>{t.aip}</p><a href="/diagnostico">{t.talk}</a></div><div className="aiOrb"><span>TC</span><b>AI</b></div></section>
<section className="sellBand"><div><small>{t.sellk}</small><h2>{t.sellt}</h2><p>{t.sellp}</p></div><a href="/anunciar">{t.sellb}</a></section>
<footer className="premiumFooter"><div className="premiumLogo"><span>TOTAL</span> CARS<em>.CH</em></div><div>Total Cars Switzerland</div><small>© 2026 Total Cars Switzerland</small></footer></main>}
