import {NextResponse} from "next/server";
const LANGS=new Set(["pt","de","fr","it","en","es"]);
const clean=(v="",n=80)=>String(v).trim().slice(0,n).replace(/[<>]/g,"");
async function search(q,lang,limit=50){const p=new URLSearchParams({action:"wbsearchentities",search:q,language:lang,uselang:lang,format:"json",origin:"*",limit:String(limit),type:"item"});const r=await fetch("https://www.wikidata.org/w/api.php?"+p,{headers:{"User-Agent":"TotalCarsSwitzerland/3.0 (info@totalcars.ch)"},next:{revalidate:86400}});if(!r.ok)throw Error("search "+r.status);return (await r.json()).search||[]}
async function get(ids,lang){if(!ids.length)return{};const p=new URLSearchParams({action:"wbgetentities",ids:ids.slice(0,50).join("|"),props:"labels|descriptions|claims|sitelinks",languages:lang+"|en|de|pt",format:"json",origin:"*"});const r=await fetch("https://www.wikidata.org/w/api.php?"+p,{headers:{"User-Agent":"TotalCarsSwitzerland/3.0 (info@totalcars.ch)"},next:{revalidate:86400}});if(!r.ok)throw Error("entities "+r.status);return (await r.json()).entities||{}}
const ids=(e,p)=>(e?.claims?.[p]||[]).map(x=>x?.mainsnak?.datavalue?.value?.id).filter(Boolean);
const id=(e,p)=>ids(e,p)[0]||"";
const str=(e,p)=>{const v=e?.claims?.[p]?.[0]?.mainsnak?.datavalue?.value;return typeof v==="string"?v:""};
const year=(e,p)=>{const t=e?.claims?.[p]?.[0]?.mainsnak?.datavalue?.value?.time||"";return (t.match(/[+-](\\d{4})-/)||[])[1]||""};
const label=(e,l)=>e?.labels?.[l]?.value||e?.labels?.en?.value||e?.labels?.de?.value||e?.labels?.pt?.value||"";
const img=n=>n?"https://commons.wikimedia.org/wiki/Special:Redirect/file/"+encodeURIComponent(n.replace(/ /g,"_")):"";
export async function GET(req){const u=new URL(req.url),brand=clean(u.searchParams.get("brand")||""),model=clean(u.searchParams.get("model")||""),lang=LANGS.has(u.searchParams.get("lang"))?u.searchParams.get("lang"):"pt";if(!brand)return NextResponse.json({success:false,error:"Escolha uma marca."},{status:400});
try{const term=model?brand+" "+model:brand;const hits=await search(term,lang,50);const es=await get(hits.map(x=>x.id),lang);const makerIds=[...new Set(Object.values(es).flatMap(e=>ids(e,"P176")))];const makers=await get(makerIds,lang);const items=hits.map(h=>{const e=es[h.id];if(!e)return null;const d=e.descriptions?.[lang]?.value||e.descriptions?.en?.value||h.description||"";const maker=id(e,"P176"),makerName=label(makers[maker],lang);const automotive=makerName.toLowerCase().includes(brand.toLowerCase())||d.toLowerCase().match(/car|automobile|vehicle|voiture|automóvel|auto|fahrzeug|wagen|suv|sedan|coupé|roadster/);if(!automotive)return null;return{id:h.id,name:label(e,lang)||h.label,description:d,manufacturer:makerName,imageUrl:img(str(e,"P18")),startYear:year(e,"P571"),endYear:year(e,"P576"),country:id(e,"P17"),article:e.sitelinks?.[lang+"wiki"]?.title||e.sitelinks?.enwiki?.title||""}}).filter(Boolean);return NextResponse.json({success:true,brand,model,count:items.length,items});}catch(e){console.error(e);return NextResponse.json({success:false,error:"Fonte histórica indisponível agora.",items:[]},{status:502})}}