"use client";
import {useState} from "react";
const brands=[["Audi","Alemanha"],["BMW","Alemanha"],["Mercedes-Benz","Alemanha"],["Porsche","Alemanha"],["Volkswagen","Alemanha"],["Opel","Alemanha"],["Ferrari","Itália"],["Lamborghini","Itália"],["Maserati","Itália"],["Alfa Romeo","Itália"],["Fiat","Itália"],["Lancia","Itália"],["Peugeot","França"],["Renault","França"],["Citroën","França"],["Bugatti","França"],["Alpine","França"],["Aston Martin","Reino Unido"],["Bentley","Reino Unido"],["Rolls-Royce","Reino Unido"],["Jaguar","Reino Unido"],["Land Rover","Reino Unido"],["McLaren","Reino Unido"],["Lotus","Reino Unido"],["MINI","Reino Unido"],["Volvo","Suécia"],["Saab","Suécia"],["Koenigsegg","Suécia"],["Škoda","Tchéquia"],["SEAT","Espanha"],["Cupra","Espanha"],["Dacia","Romênia"],["Toyota","Japão"],["Lexus","Japão"],["Honda","Japão"],["Acura","Japão"],["Nissan","Japão"],["Infiniti","Japão"],["Mazda","Japão"],["Subaru","Japão"],["Mitsubishi","Japão"],["Suzuki","Japão"],["Isuzu","Japão"],["Hyundai","Coreia do Sul"],["Kia","Coreia do Sul"],["Genesis","Coreia do Sul"],["Ford","Estados Unidos"],["Chevrolet","Estados Unidos"],["Cadillac","Estados Unidos"],["Buick","Estados Unidos"],["Chrysler","Estados Unidos"],["Dodge","Estados Unidos"],["Jeep","Estados Unidos"],["Lincoln","Estados Unidos"],["Tesla","Estados Unidos"],["Rivian","Estados Unidos"],["Lucid","Estados Unidos"],["BYD","China"],["Geely","China"],["NIO","China"],["XPeng","China"],["Chery","China"],["Hongqi","China"],["Great Wall","China"],["MG","China"]];
export default function Historia(){
 const [brand,setBrand]=useState(""),[model,setModel]=useState(""),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function load(b,m=""){setBrand(b);setModel(m);setLoading(true);setError("");try{const r=await fetch("/api/car-history?brand="+encodeURIComponent(b)+(m?"&model="+encodeURIComponent(m):""));const d=await r.json();if(!r.ok)throw Error(d.error||"Falha");setItems(d.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 function back(){if(model){setModel("");load(brand)}else{setBrand("");setItems([])}}
 return <main className="historyPage">
  <header className="historyTop"><a className="historyLogo" href="/"><b>TOTAL <i>CARS</i></b><small>SWITZERLAND CH</small></a><nav><a href="/">INÍCIO</a><a href="/comprar">CARROS</a><a href="/diagnostico">DIAGNÓSTICO</a><a href="/revista">REVISTA</a></nav></header>
  <section className="historyHero"><button className="historyBack" onClick={()=>brand?back():history.back()}>← VOLTAR</button><small>ENCICLOPÉDIA TOTAL CARS</small><h1>{model?brand+" "+model:brand||"História dos Carros"}</h1><p>{model?"História, evolução, anos e registros visuais do modelo.":brand?"Explore os modelos e a evolução histórica da "+brand+".":"Escolha uma marca. Depois abra um modelo para acompanhar sua evolução, anos e imagens."}</p></section>
  <section className="historyBody">
   {!brand&&<><div className="historyTitle"><span>MARCAS DO MUNDO</span><h2>Escolha a marca</h2></div><div className="brandGrid">{brands.map(([b,c])=><button key={b} onClick={()=>load(b)}><strong>{b}</strong><span>{c}</span><i>→</i></button>)}</div></>}
   {brand&&<><div className="historyToolbar"><button onClick={back}>← {model?"VOLTAR PARA "+brand:"TODAS AS MARCAS"}</button><form onSubmit={e=>{e.preventDefault();load(brand,model)}}><input value={model} onChange={e=>setModel(e.target.value)} placeholder={"Pesquisar modelo da "+brand}/><button>BUSCAR MODELO</button></form></div>
   {loading&&<div className="historyStatus">Montando a história...</div>}{error&&<div className="historyStatus">{error}</div>}
   {!loading&&items.length>0&&<><div className="historyTitle"><span>{model?"EVOLUÇÃO DO MODELO":"ARQUIVO DA MARCA"}</span><h2>{model?brand+" "+model:"Modelos históricos da "+brand}</h2><p>{items.length} registros históricos encontrados.</p></div><div className="modelGrid">{items.map((x,n)=><article key={x.id}><div className="modelPhoto">{x.imageUrl?<img src={x.imageUrl} alt={x.name}/>:<span>IMAGEM NÃO DISPONÍVEL</span>}<b>{x.startYear||"ANO —"}</b></div><div className="modelCopy"><small>REGISTRO {String(n+1).padStart(2,"0")}</small><h3>{x.name}</h3><p>{x.description||("Veículo associado à "+brand+" nas fontes históricas abertas.")}</p><div className="facts"><span><b>INÍCIO</b>{x.startYear||"—"}</span><span><b>FIM</b>{x.endYear||"—"}</span><span><b>MARCA</b>{brand}</span></div>{!model&&<button onClick={()=>{setModel(x.name.replace(new RegExp("^"+brand+"\\s*","i"),""));load(brand,x.name.replace(new RegExp("^"+brand+"\\s*","i"),""))}}>ABRIR HISTÓRIA →</button>}</div></article>)}</div></>}
   {!loading&&items.length===0&&!error&&<div className="historyStatus">Nenhum registro confirmado encontrado. O Total Cars não inventa dados.</div>}</>}
  </section>
 </main>
}