"use client";
import {useState} from "react";
const brands=[
["Audi","Alemanha"],["BMW","Alemanha"],["Mercedes-Benz","Alemanha"],["Porsche","Alemanha"],["Volkswagen","Alemanha"],["Opel","Alemanha"],
["Ferrari","Itália"],["Lamborghini","Itália"],["Maserati","Itália"],["Alfa Romeo","Itália"],["Fiat","Itália"],["Lancia","Itália"],
["Peugeot","França"],["Renault","França"],["Citroën","França"],["Bugatti","França"],["Alpine","França"],
["Aston Martin","Reino Unido"],["Bentley","Reino Unido"],["Rolls-Royce","Reino Unido"],["Jaguar","Reino Unido"],["Land Rover","Reino Unido"],["McLaren","Reino Unido"],["Lotus","Reino Unido"],["MINI","Reino Unido"],
["Volvo","Suécia"],["Saab","Suécia"],["Koenigsegg","Suécia"],["Škoda","Tchéquia"],["SEAT","Espanha"],["Cupra","Espanha"],["Dacia","Romênia"],
["Toyota","Japão"],["Lexus","Japão"],["Honda","Japão"],["Acura","Japão"],["Nissan","Japão"],["Infiniti","Japão"],["Mazda","Japão"],["Subaru","Japão"],["Mitsubishi","Japão"],["Suzuki","Japão"],["Isuzu","Japão"],
["Hyundai","Coreia do Sul"],["Kia","Coreia do Sul"],["Genesis","Coreia do Sul"],
["Ford","Estados Unidos"],["Chevrolet","Estados Unidos"],["Cadillac","Estados Unidos"],["Buick","Estados Unidos"],["Chrysler","Estados Unidos"],["Dodge","Estados Unidos"],["Jeep","Estados Unidos"],["Lincoln","Estados Unidos"],["Tesla","Estados Unidos"],["Rivian","Estados Unidos"],["Lucid","Estados Unidos"],
["BYD","China"],["Geely","China"],["NIO","China"],["XPeng","China"],["Chery","China"],["Hongqi","China"],["Great Wall","China"],["MG","China"]
];
export default function Historia(){
 const [brand,setBrand]=useState(""),[model,setModel]=useState(""),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function openBrand(b,m=""){setBrand(b);setModel(m);setLoading(true);setError("");try{const r=await fetch("/api/car-history?brand="+encodeURIComponent(b)+(m?"&model="+encodeURIComponent(m):"")+"&lang=pt");const d=await r.json();if(!r.ok)throw Error(d.error||"Falha");setItems(d.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 const years=[...items].sort((a,b)=>(a.startYear||"9999").localeCompare(b.startYear||"9999"));
 return <main style={{maxWidth:1240,margin:"0 auto",padding:"28px 20px 70px",fontFamily:"Arial,sans-serif",color:"#111"}}>
  <a href="/" style={{fontWeight:900,textDecoration:"none",color:"inherit"}}>← TOTALCARS.CH</a>
  <header style={{padding:"34px 0 22px",borderBottom:"1px solid #ddd"}}><small style={{fontWeight:900,letterSpacing:2}}>ENCICLOPÉDIA TOTAL CARS</small><h1 style={{fontSize:"clamp(42px,7vw,82px)",lineHeight:.9,margin:"8px 0 14px"}}>História dos Carros</h1><p style={{fontSize:19,maxWidth:800,color:"#555"}}>Escolha uma marca para viajar pela sua história. Depois escolha o modelo e acompanhe sua evolução por gerações e anos.</p></header>
  {!brand&&<><h2 style={{marginTop:32}}>Escolha a marca</h2><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(180px,1fr))",gap:12}}>{brands.map(([b,c])=><button key={b} onClick={()=>openBrand(b)} style={{textAlign:"left",padding:20,border:"1px solid #ddd",borderRadius:14,background:"#fff",cursor:"pointer"}}><b style={{fontSize:19}}>{b}</b><br/><small style={{color:"#777"}}>{c}</small></button>)}</section></>}
  {brand&&<><button onClick={()=>{setBrand("");setModel("");setItems([])}} style={{marginTop:26,border:0,background:"none",fontWeight:900,cursor:"pointer"}}>← TODAS AS MARCAS</button><section style={{padding:"24px 0"}}><small>HISTÓRIA DA MARCA</small><h2 style={{fontSize:"clamp(38px,6vw,70px)",margin:"4px 0"}}>{brand}</h2><p style={{color:"#555"}}>Linha histórica de veículos, modelos e gerações encontrados nas fontes abertas. Selecione ou pesquise um modelo para aprofundar.</p><form onSubmit={e=>{e.preventDefault();openBrand(brand,model)}} style={{display:"flex",gap:8,flexWrap:"wrap"}}><input value={model} onChange={e=>setModel(e.target.value)} placeholder={"Ex.: "+(brand==="Audi"?"A6":brand==="BMW"?"M3":"modelo")} style={{flex:"1 1 280px",padding:15,border:"1px solid #bbb",borderRadius:10}}/><button style={{padding:"15px 22px",border:0,borderRadius:10,fontWeight:900}}>VER HISTÓRIA DO MODELO</button></form></section>
  {loading&&<p>Montando a linha do tempo...</p>}{error&&<p>{error}</p>}
  {!loading&&years.length>0&&<section><h3>{model?("Evolução do "+brand+" "+model):("Modelos históricos da "+brand)}</h3><div style={{borderLeft:"3px solid #111",marginLeft:10,paddingLeft:24}}>{years.map(x=><article key={x.id} style={{display:"grid",gridTemplateColumns:"minmax(90px,140px) 1fr",gap:18,padding:"18px 0",borderBottom:"1px solid #eee"}}><div><b style={{fontSize:22}}>{x.startYear||"—"}</b>{x.endYear&&<div>até {x.endYear}</div>}</div><div style={{display:"grid",gridTemplateColumns:x.imageUrl?"150px 1fr":"1fr",gap:16}}>{x.imageUrl&&<img src={x.imageUrl} alt={x.name} style={{width:150,height:95,objectFit:"cover",borderRadius:10}}/>}<div><h4 style={{fontSize:22,margin:"0 0 6px"}}>{x.name}</h4><p style={{margin:0,color:"#555"}}>{x.description||"Registro histórico confirmado na fonte aberta."}</p></div></div></article>)}</div></section>}
  {!loading&&brand&&years.length===0&&!error&&<p style={{padding:"28px 0",color:"#666"}}>Nenhum registro confirmado foi encontrado para esta seleção. Não vamos inventar gerações ou datas.</p>}</>}
  <footer style={{marginTop:48,paddingTop:20,borderTop:"1px solid #ddd",fontSize:13,color:"#777"}}>História dos Carros · Total Cars Switzerland · dados históricos enriquecidos a partir de fontes abertas.</footer>
 </main>
}