export const magazineStories=[
{section:"MUNDO",title:"BMW redesenha sua estratégia global",deck:"Novos modelos, eficiência e inteligência artificial entram no centro do próximo ciclo da marca.",body:["A BMW apresentou uma revisão de estratégia com simplificação da organização e maior uso de IA. Na Europa, a empresa prevê um elétrico de entrada da Neue Klasse para 2028.","Na China, a fabricante quer ampliar a localização de produtos e produção. A mudança mostra a pressão por ciclos de desenvolvimento mais rápidos."],source:"Reuters · 30/09/2026"},
{section:"MUNDO",title:"Tesla volta a ganhar ritmo na Europa",deck:"Registros cresceram em vários mercados europeus em setembro.",body:["Dados publicados pela Reuters apontam crescimento anual em mercados como França, Suécia e Espanha.","A disputa continua mais intensa com novos elétricos europeus e a expansão das fabricantes chinesas."],source:"Reuters · 01/10/2026"},
{section:"LANÇAMENTOS",title:"Aston Martin DBX GT mira viagens de luxo",deck:"Nova versão do SUV V8 aposta em suspensão mais confortável e cabine refinada.",body:["A Autocar apresentou o DBX GT como uma alternativa mais voltada a longas viagens dentro da família do SUV britânico.","A proposta mostra como SUVs de alta performance estão ganhando versões que equilibram desempenho e conforto."],source:"Autocar · 01/10/2026"},
{section:"LANÇAMENTOS",title:"BMW X3 M50 ganha mais potência",deck:"O seis-cilindros turbo chega a 437 bhp na atualização divulgada pela Autocar.",body:["O X3 M50 continua ocupando o espaço de alto desempenho abaixo de um X3 M completo.","Mesmo com a eletrificação acelerando, motores de seis cilindros seguem recebendo desenvolvimento no segmento premium."],source:"Autocar · 01/10/2026"},
{section:"ELÉTRICOS",title:"Range Rover Sport entra na era elétrica",deck:"O SUV premium ganha versão totalmente elétrica com forte foco em desempenho.",body:["A Autocar informa autonomia anunciada de 374 milhas e preço britânico na faixa de 110 mil libras.","O modelo coloca a Land Rover diretamente na disputa dos grandes SUVs elétricos premium."],source:"Autocar · 30/09/2026"},
{section:"ELÉTRICOS",title:"Renault Mégane EV fica mais competitivo",deck:"Atualização e incentivo britânico reduzem o preço de entrada do elétrico.",body:["Segundo a Autocar, o Mégane renovado parte de cerca de 28 mil libras no Reino Unido após incentivo elegível.","O caso mostra como incentivos ainda podem alterar rapidamente a comparação de preço entre elétricos."],source:"Autocar · 01/10/2026"},
{section:"CHINA & ÁSIA",title:"China muda o equilíbrio da indústria",deck:"Velocidade de desenvolvimento, escala e tecnologia aumentam a pressão sobre fabricantes tradicionais.",body:["Executivos globais vêm destacando o avanço das montadoras chinesas e seus ciclos curtos de produto.","A competição envolve preço, software, baterias, recarga e velocidade para lançar novas plataformas."],source:"Reuters · 29/09/2026"},
{section:"CHINA & ÁSIA",title:"iCaur prepara expansão europeia",deck:"A marca de aventura do grupo Chery avança em sua preparação para o Reino Unido.",body:["A Autocar relata apresentações a concessionários e preparação de uma rede para a marca conhecida como iCar na China.","A estratégia ilustra como grandes grupos chineses usam marcas diferentes para públicos e segmentos específicos."],source:"Autocar · 29/09/2026"},
{section:"TECNOLOGIA",title:"Stellantis e Momenta ampliam direção inteligente",deck:"Parceria na China vai desenvolver assistência avançada para marcas do grupo.",body:["A cooperação envolve a joint venture da Stellantis com a Dongfeng e a empresa chinesa de software Momenta.","Jeep e Peugeot estão entre as marcas citadas para integração dessas tecnologias."],source:"Reuters · 28/09/2026"},
{section:"TECNOLOGIA",title:"Recarga ultrarrápida vira nova corrida",deck:"Geely mostrou tecnologia que promete reduzir drasticamente a parada no carregador.",body:["A Top Gear destacou um sistema anunciado com recarga de 10% a 70% em menos de cinco minutos em condições específicas.","Resultados reais dependem do veículo, bateria, temperatura e infraestrutura, mas a direção tecnológica é clara."],source:"Top Gear · 24/09/2026"},
{section:"SUPERCARROS",title:"Bentley estreia sua fase elétrica",deck:"O Torcal leva a interpretação de luxo da marca para uma arquitetura elétrica.",body:["A Autocar descreve o modelo como um SUV elétrico de alto desempenho com autonomia anunciada próxima de 375 milhas.","No luxo, a transição envolve também recriar sensação, acabamento e identidade de marca."],source:"Autocar · 23/09/2026"},
{section:"CLÁSSICOS",title:"Porsche 944 vira shooting brake artesanal",deck:"O GT-K44 transforma o esportivo clássico em um raro projeto de carroceria alongada.",body:["A Top Gear apresentou o restomod com preço acima de 100 mil euros.","Projetos assim unem desenho histórico, engenharia moderna e produção muito limitada."],source:"Top Gear · 01/10/2026"}
];